# Generated by Django 6.1 on 2026-09-04 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zayavka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Легковой', 'Легковой'), ('Грузовой', 'Грузовой'), ('Тягач', 'Тягач')], max_length=30, verbose_name='Тип авто')),
                ('datetime', models.DateTimeField(verbose_name='Дата и время записи')),
                ('payment', models.CharField(choices=[('Налик', 'Налик'), ('Картой', 'Картой'), ('СБП', 'СБП')], max_length=30, verbose_name='Способ оплаты')),
                ('status', models.CharField(choices=[('Ожидание ответа', 'Ожидание ответа'), ('В обработке', 'В обработке'), ('Услуга оказана', 'Услуга оказана')], default='Ожидание ответа', max_length=30, verbose_name='Статус заявки')),
            ],
        ),
    ]
